on: 
  push:
      paths: 
          - '**/buildmerge.yml'
    #branches: 
      #- master

jobs:

  build-normal:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - name: logging
        run: |
          buiii
          echo "$GITHUB_REF"
  
   
