name: refs/pull/:prNumber/merge


on:

  push:

    branches: 

      - refs/pull/4/merge

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: logging

        run: echo "$GITHUB_REF"
