name: refs/pull/:prNumber/merge


on: registry_package
  #push:
    #branches: 
      #- master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: logging

        run: echo "$GITHUB_REF"
      - uses: actions/checkout@v1
        with:
          ref: refs/pull/4/merge
