name: add path
on: push
env:
        ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}

jobs:
  job1:
   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: add path
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        echo "echo Hello, world!" > $GITHUB_WORKSPACE/bin/hello-world
        echo "::add-path::$GITHUB_WORKSPACE/bin"
        chmod +x $GITHUB_WORKSPACE/bin/hello-world
    #- name: Make hello-world executable
    #  run: chmod +x $GITHUB_WORKSPACE/bin/hello-world
    - name: Use program
      run: hello-world
    
     
