name: linux self-hosted runner
on: push

jobs:
  self-hosted-env-alpine:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: docker://alpine
        with:
          args: sh -c "pwd && env"
      - uses: docker://alpine
        name: alpine workspace
        with:
          args: ls -lat

     
