name: add path
on: push

jobs:
  job1:
   
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ '0.2' }}
      NAME: ${{ 'subsurface/mxe-build-container:$VERSION.stage1' }}
   
    steps:
    - uses: actions/checkout@v1
    - run: echo 'version'  $VERSION  'name' + $NAME
      env:
        NAME: ${{ format(subsurface/mxe-build-container:{0}.stage1',${{env.VERSION}}) }}
    - name: add path
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        echo "echo Hello, world!" > $GITHUB_WORKSPACE/bin/hello-world
        echo "::add-path::$GITHUB_WORKSPACE/bin"
        chmod +x $GITHUB_WORKSPACE/bin/hello-world
    - name: Use program
      run: hello-world
    
     
