name: add path
on: push

jobs:
  job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: add path
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        echo "echo Hello, world!" > $GITHUB_WORKSPACE/bin/hello-world
        echo "::add-path::$GITHUB_WORKSPACE/bin"
    - name: Use program
      run: hello-world
     
