name: self-hosted runner
on: push
#1 2
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - run: export $(grep -v '^#' use.env | xargs)
      - name: Dump Env context
        env: 
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
      
