name: linux self-hosted runner
on: push

jobs:
  self-hosted-env-alpine:
    runs-on: [self-hosted, windows]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - run: |
          hostname
      - run: set

        shell: cmd   
     
