name: self-hosted runner
on: check_run
#1 2
jobs:
  job1:
    runs-on: self-hosted
    steps: 
    

 
      - run: Write-Host "$($PSVersionTable.PSVersion)"
        working-directory: C:\Program Files\PowerShell\7-preview\
