name: linux self-hosted runner
on: push

jobs:
  self-hosted-env-alpine:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - run: |
          sudo /usr/bin/docker pull alpine  sh -c "pwd && env"
      #- uses: docker://alpine
      #  name: alpine workspace
       # with:
      #   args: ls -lat
# containner 3 4

     
