name: Merge PR


on:
  push:
    branches: ['release/*']

jobs:
  merge-PR:
    #if: github.event.pull_request.merged == true
   
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: zhu5201314/DockerContainer_action@master
        with:
          who-to-greet: 'Mona the Octocat'
