name: test my FirstJSAction
on:   push
jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
    - run: wmic pagefile list /format:list   
    - name: Hello world action step
      id: hello
      uses: zhu5201314/FirstJSAction@master
      with:
        who-to-greet: ${{ github.event_name != 'schedule2' }}
  
