name: test my FirstJSAction
on:   push

jobs:
  testps:
    runs-on: windows-latest
    steps:
    - name: PS Version
      run: $PSVersionTable.PSVersion
      shell: powershell
    - name: Build
      run: where.exe tar
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: zhu5201314/FirstJSAction@1
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
