name: test my FirstJSAction
on:   push
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
       
    - name: Hello world action step
      id: hello
      uses: zhu5201314/FirstJSAction@v2
      with:
        who-to-greet: ${{ github.event_name != 'schedule' }}
  
