name: matrix

on: push

jobs:

  job_name:

    name: Run sanity tests in collections

    runs-on: ${{ matrix.vm }}
    
    container: ${{ matrix.image }}

    strategy:

      matrix:
        vm: [ubuntu-latest,ubuntu-16.04, macos-latest]
        image: [ 'quay.io/ansible/default-test-container:1.10.1' ]


    steps:
      - run: echo hello

