name: set output 
env:
  FIREBASE_EMULATORS_PATH: ${{GITHUB.WORKSPACe}}/emulator-cach
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      id: release_description
      run: |
        echo $FIREBASE_EMULATORS_PATH
    - run:  echo $PATH
      env:
        PATH: ${{GITHUB.WORKSPACe}}/emulator-cach
    - name: 'Cache Emulators'
      uses: actions/cache@v1
      with:
        path: ${{GITHUB.WORKSPACe}}/emulator-cach
        key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('patch1.txt') }}
      continue-on-error: true

 
