name: test set output
# This workflow is triggered on pushes to the repository. 666
on:   push
jobs:
  release: 
    runs-on: windows-latest
  
    steps:
    - name: set env
      run: |
          echo "::set-env name=COMPONENTS::hhhhhhh"
    - name: use env
      run: |
         echo ${env.COMPONENTS}
        
    - run:   echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      shell: bash

    - run:   echo "$REPOSITORY_NAME"
      shell: bash
      

