
name: pull requestmerge

on:
  pull_request:
    branches: 
      - master
    types: [edited]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: output label name
        run: |
          array=$GITHUB_CONTEXT
          echo ${array[*].name}
          
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.labels) }}
