
name: pull requestmerge

on: 
 pull_request:
     types: [opened]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: current branch
      run: |
   
        echo  $LABELS
      env:
        LABELS: ${{ toJson(github.event.pull_request.labels) }}
      
