name: test set output
# This workflow is triggered on pushes to the repository. 666
on:   push
jobs:
  release: 
    runs-on: self-hosted
  
    steps:
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: ${env:RUNNER_CONTEXT}
    - name: set env
      run: |
        echo "::set-env name=COMPONENTS::$(find src/Viserio -mindepth 2 -type f -name phpunit.xml.dist -printf '%h,' | sort)"
          #echo "::set-env name=COMPONENTS::hhhhhhh"
      shell: bash
    - name: use env
      shell: powershell
      run: |
         echo ${env:COMPONENTS}
         #hhhh
        
    - run:   echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      shell: bash

    - run:   echo "$REPOSITORY_NAME"
      shell: bash
      

