# This workflow is triggered on pushes to the repository. 666 444
on:  [ push, pull_request ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: YJZ Hello World
        uses: zhu5201314/FirstJSAction@v2.0

