
name: pull requestmerge

on:
  pull_request:
    branches: 
      - master
    types: [edited]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: current branch
      run: |
        array = ${{ github.event.pull_request.labels }}
        echo "${array[*]}"
