name: workflow2

on: check_run

env:
  DOCKER_URL: some.docker.url

jobs:
  build:  
    
    runs-on: ubuntu-latest
 
    steps:
    
    - name: Step 1
      run: |
        echo $DOCKER_IMAGE
      env:
        DOCKER_IMAGE: ${{env.DOCKER_URL}}/some-namespace/some-image 
