name: test set output
# This workflow is triggered on pushes to the repository. 666
on:   push
jobs:
  release: 
    runs-on: windows-latest
  
    steps:
    - name: set env
      run: |
          echo "::set-env name=COMPONENTS::$(find src/Viserio -mindepth 2 -type f -name phpunit.xml.dist -printf '%h,' | sort)"
    - name: use env
      run: |
         ${env.COMPONENTS}.TrimEnd(",").Split(",")| ForEach {
            echo ::group::$_
            cd $_
            composer validate --strict
            $COMPOSER_UP
            $PHPUNIT
            cd $GITHUB_WORKSPACE
            echo ::endgroup::
          }
        
    - run:   echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      shell: bash

    - run:   echo "$REPOSITORY_NAME"
      shell: bash
      

